sudo: false

env:

language: php

services:

php:
  - 7.1

before_install:
  - phpize
  - ./configure
  - make
  - make install
  - echo "extension=ast.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-add php.ini.dist

install:
  - travis_retry composer selfupdate
  - travis_retry composer install --no-interaction --prefer-source

before_script:

script:
  - ./vendor/bin/php-cs-fixer fix --verbose
  - ./vendor/bin/phpunit

after_success:
after_failure:
after_script:
before_deploy:
deploy:
after_deploy:


